//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Curriculum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Curriculum()
        {
            this.tbl_CurriculumDetails = new HashSet<tbl_CurriculumDetails>();
            this.tbl_CurriculumDetails1 = new HashSet<tbl_CurriculumDetails>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.Guid CountryId { get; set; }
        public System.Guid BoardId { get; set; }
        public System.Guid StandardId { get; set; }
        public System.Guid SubjectId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tbl_Board tbl_Board { get; set; }
        public virtual tbl_Board tbl_Board1 { get; set; }
        public virtual tbl_Country tbl_Country { get; set; }
        public virtual tbl_Country tbl_Country1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CurriculumDetails> tbl_CurriculumDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CurriculumDetails> tbl_CurriculumDetails1 { get; set; }
        public virtual tbl_Standard tbl_Standard { get; set; }
        public virtual tbl_Standard tbl_Standard1 { get; set; }
        public virtual tbl_Subject tbl_Subject { get; set; }
        public virtual tbl_Subject tbl_Subject1 { get; set; }
    }
}
