//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CurriculumDetails
    {
        public System.Guid Id { get; set; }
        public System.Guid CurriculumId { get; set; }
        public System.Guid TopicId { get; set; }
        public Nullable<System.Guid> SubTopicId { get; set; }
        public Nullable<System.Guid> CategoryId { get; set; }
        public Nullable<System.Guid> LevelId { get; set; }
    
        public virtual tbl_Category_SubTopic tbl_Category_SubTopic { get; set; }
        public virtual tbl_Curriculum tbl_Curriculum { get; set; }
        public virtual tbl_Curriculum tbl_Curriculum1 { get; set; }
        public virtual tbl_Level tbl_Level { get; set; }
        public virtual tbl_SubTopic tbl_SubTopic { get; set; }
        public virtual tbl_Topic tbl_Topic { get; set; }
    }
}
