//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Quiz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Quiz()
        {
            this.tbl_MapTeacherStudentQuiz = new HashSet<tbl_MapTeacherStudentQuiz>();
            this.tbl_MapTeacherStudentQuiz1 = new HashSet<tbl_MapTeacherStudentQuiz>();
            this.tbl_QuizDetails = new HashSet<tbl_QuizDetails>();
            this.tbl_QuizDetails1 = new HashSet<tbl_QuizDetails>();
            this.tbl_QuizResponse = new HashSet<tbl_QuizResponse>();
            this.tbl_QuizResponse1 = new HashSet<tbl_QuizResponse>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid StandardId { get; set; }
        public System.Guid SubjectId { get; set; }
        public System.Guid TopicId { get; set; }
        public Nullable<System.Guid> SubTopicId { get; set; }
        public Nullable<System.Guid> CategoryId { get; set; }
        public Nullable<long> TotalQuestions { get; set; }
        public Nullable<long> Duration { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual tbl_Category_SubTopic tbl_Category_SubTopic { get; set; }
        public virtual tbl_Category_SubTopic tbl_Category_SubTopic1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MapTeacherStudentQuiz> tbl_MapTeacherStudentQuiz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MapTeacherStudentQuiz> tbl_MapTeacherStudentQuiz1 { get; set; }
        public virtual tbl_Standard tbl_Standard { get; set; }
        public virtual tbl_Standard tbl_Standard1 { get; set; }
        public virtual tbl_Subject tbl_Subject { get; set; }
        public virtual tbl_Subject tbl_Subject1 { get; set; }
        public virtual tbl_SubTopic tbl_SubTopic { get; set; }
        public virtual tbl_SubTopic tbl_SubTopic1 { get; set; }
        public virtual tbl_Topic tbl_Topic { get; set; }
        public virtual tbl_Topic tbl_Topic1 { get; set; }
        public virtual tbl_User tbl_User { get; set; }
        public virtual tbl_User tbl_User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_QuizDetails> tbl_QuizDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_QuizDetails> tbl_QuizDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_QuizResponse> tbl_QuizResponse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_QuizResponse> tbl_QuizResponse1 { get; set; }
    }
}
