//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserDetails
    {
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<System.Guid> CountryId { get; set; }
        public Nullable<System.Guid> StateId { get; set; }
        public Nullable<System.Guid> CityId { get; set; }
        public Nullable<System.Guid> LocationId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.Guid SubjectId { get; set; }
    
        public virtual tbl_City tbl_City { get; set; }
        public virtual tbl_City tbl_City1 { get; set; }
        public virtual tbl_Country tbl_Country { get; set; }
        public virtual tbl_Country tbl_Country1 { get; set; }
        public virtual tbl_Location tbl_Location { get; set; }
        public virtual tbl_Location tbl_Location1 { get; set; }
        public virtual tbl_State tbl_State { get; set; }
        public virtual tbl_State tbl_State1 { get; set; }
        public virtual tbl_Subject tbl_Subject { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
