//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_User()
        {
            this.tbl_Map_Role_User = new HashSet<tbl_Map_Role_User>();
            this.tbl_Map_School_Teacher = new HashSet<tbl_Map_School_Teacher>();
            this.tbl_Map_Teacher_Standard = new HashSet<tbl_Map_Teacher_Standard>();
            this.tbl_Map_User_Section = new HashSet<tbl_Map_User_Section>();
            this.tbl_Map_User_Section1 = new HashSet<tbl_Map_User_Section>();
            this.tbl_MapParentChild = new HashSet<tbl_MapParentChild>();
            this.tbl_MapParentChild1 = new HashSet<tbl_MapParentChild>();
            this.tbl_MapSchoolTeacherStandard = new HashSet<tbl_MapSchoolTeacherStandard>();
            this.tbl_MapTeacherChild = new HashSet<tbl_MapTeacherChild>();
            this.tbl_MapTeacherChild1 = new HashSet<tbl_MapTeacherChild>();
            this.tbl_MapTeacherStudentQuiz = new HashSet<tbl_MapTeacherStudentQuiz>();
            this.tbl_MapTeacherStudentQuiz1 = new HashSet<tbl_MapTeacherStudentQuiz>();
            this.tbl_MapTeacherStudentQuiz2 = new HashSet<tbl_MapTeacherStudentQuiz>();
            this.tbl_MapTeacherStudentQuiz3 = new HashSet<tbl_MapTeacherStudentQuiz>();
            this.tbl_Quiz = new HashSet<tbl_Quiz>();
            this.tbl_Quiz1 = new HashSet<tbl_Quiz>();
            this.tbl_QuizResponse = new HashSet<tbl_QuizResponse>();
            this.tbl_QuizResponse1 = new HashSet<tbl_QuizResponse>();
            this.tbl_UserDetails = new HashSet<tbl_UserDetails>();
        }
    
        public System.Guid Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Address1 { get; set; }
        public string Mobile { get; set; }
        public string Address2 { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public string LoginId { get; set; }
        public string Pwd { get; set; }
        public Nullable<System.Guid> StandardId { get; set; }
        public Nullable<System.Guid> Qualification { get; set; }
        public Nullable<System.Guid> CountryId { get; set; }
        public Nullable<System.Guid> StateId { get; set; }
        public Nullable<System.Guid> CityId { get; set; }
        public Nullable<System.Guid> LocationId { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string AlternatePhone { get; set; }
        public string AlternateEmail { get; set; }
        public Nullable<bool> EmailVerified { get; set; }
        public string Occupation { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Location { get; set; }
        public string PinCode { get; set; }
        public string Subjects { get; set; }
        public Nullable<System.Guid> BoardId { get; set; }
        public string ImageB64 { get; set; }
        public Nullable<System.Guid> SchoolId { get; set; }
        public Nullable<int> ChildAllowed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Map_Role_User> tbl_Map_Role_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Map_School_Teacher> tbl_Map_School_Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Map_Teacher_Standard> tbl_Map_Teacher_Standard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Map_User_Section> tbl_Map_User_Section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Map_User_Section> tbl_Map_User_Section1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MapParentChild> tbl_MapParentChild { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MapParentChild> tbl_MapParentChild1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MapSchoolTeacherStandard> tbl_MapSchoolTeacherStandard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MapTeacherChild> tbl_MapTeacherChild { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MapTeacherChild> tbl_MapTeacherChild1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MapTeacherStudentQuiz> tbl_MapTeacherStudentQuiz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MapTeacherStudentQuiz> tbl_MapTeacherStudentQuiz1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MapTeacherStudentQuiz> tbl_MapTeacherStudentQuiz2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MapTeacherStudentQuiz> tbl_MapTeacherStudentQuiz3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Quiz> tbl_Quiz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Quiz> tbl_Quiz1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_QuizResponse> tbl_QuizResponse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_QuizResponse> tbl_QuizResponse1 { get; set; }
        public virtual tbl_School tbl_School { get; set; }
        public virtual tbl_School tbl_School1 { get; set; }
        public virtual tbl_Standard tbl_Standard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UserDetails> tbl_UserDetails { get; set; }
    }
}
