//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MapSchoolTeacherStandard
    {
        public System.Guid SchoolId { get; set; }
        public System.Guid TeacherId { get; set; }
        public System.Guid StandardId { get; set; }
        public System.Guid SubjectId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.Guid UpdatedBy { get; set; }
    
        public virtual tbl_School tbl_School { get; set; }
        public virtual tbl_Standard tbl_Standard { get; set; }
        public virtual tbl_Subject tbl_Subject { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
