//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Question_Pattern
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Question_Pattern()
        {
            this.tbl_Solutions = new HashSet<tbl_Solutions>();
            this.tbl_Solutions1 = new HashSet<tbl_Solutions>();
        }
    
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string Pattern { get; set; }
        public System.Guid TopicId { get; set; }
        public System.Guid Sub_TopicId { get; set; }
        public System.Guid Category_SubTopicId { get; set; }
        public System.Guid LevelId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.Guid> BoardId { get; set; }
        public System.Guid SubjectId { get; set; }
        public Nullable<System.Guid> StandardId { get; set; }
    
        public virtual tbl_Category_SubTopic tbl_Category_SubTopic { get; set; }
        public virtual tbl_Level tbl_Level { get; set; }
        public virtual tbl_SubTopic tbl_SubTopic { get; set; }
        public virtual tbl_Subject tbl_Subject { get; set; }
        public virtual tbl_Topic tbl_Topic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Solutions> tbl_Solutions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Solutions> tbl_Solutions1 { get; set; }
    }
}
