//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Standard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Standard()
        {
            this.tbl_Curriculum = new HashSet<tbl_Curriculum>();
            this.tbl_Curriculum1 = new HashSet<tbl_Curriculum>();
            this.tbl_Map_School_Standard = new HashSet<tbl_Map_School_Standard>();
            this.tbl_Map_Teacher_Standard = new HashSet<tbl_Map_Teacher_Standard>();
            this.tbl_Map_User_Section = new HashSet<tbl_Map_User_Section>();
            this.tbl_Map_User_Section1 = new HashSet<tbl_Map_User_Section>();
            this.tbl_MapSchoolTeacherStandard = new HashSet<tbl_MapSchoolTeacherStandard>();
            this.tbl_Quiz = new HashSet<tbl_Quiz>();
            this.tbl_Quiz1 = new HashSet<tbl_Quiz>();
            this.tbl_User = new HashSet<tbl_User>();
            this.tbl_Standard_Level_Board_Mapping = new HashSet<tbl_Standard_Level_Board_Mapping>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string TypeName { get; set; }
        public Nullable<System.Guid> BoardId { get; set; }
    
        public virtual tbl_Board tbl_Board { get; set; }
        public virtual tbl_Board tbl_Board1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Curriculum> tbl_Curriculum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Curriculum> tbl_Curriculum1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Map_School_Standard> tbl_Map_School_Standard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Map_Teacher_Standard> tbl_Map_Teacher_Standard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Map_User_Section> tbl_Map_User_Section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Map_User_Section> tbl_Map_User_Section1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MapSchoolTeacherStandard> tbl_MapSchoolTeacherStandard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Quiz> tbl_Quiz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Quiz> tbl_Quiz1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_User> tbl_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Standard_Level_Board_Mapping> tbl_Standard_Level_Board_Mapping { get; set; }
    }
}
