//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Map_User_Section
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> SubjectId { get; set; }
        public System.Guid SectionId { get; set; }
        public Nullable<System.Guid> StandardId { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tbl_ParamDetail tbl_ParamDetail { get; set; }
        public virtual tbl_ParamDetail tbl_ParamDetail1 { get; set; }
        public virtual tbl_Standard tbl_Standard { get; set; }
        public virtual tbl_Standard tbl_Standard1 { get; set; }
        public virtual tbl_Subject tbl_Subject { get; set; }
        public virtual tbl_Subject tbl_Subject1 { get; set; }
        public virtual tbl_User tbl_User { get; set; }
        public virtual tbl_User tbl_User1 { get; set; }
    }
}
