//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PCM_LearningBuddyEntities : DbContext
    {
        public PCM_LearningBuddyEntities()
            : base("name=PCM_LearningBuddyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Mailer> tbl_Mailer { get; set; }
        public virtual DbSet<tbl_AccessToken> tbl_AccessToken { get; set; }
        public virtual DbSet<tbl_Board> tbl_Board { get; set; }
        public virtual DbSet<tbl_Category> tbl_Category { get; set; }
        public virtual DbSet<tbl_Category_SubTopic> tbl_Category_SubTopic { get; set; }
        public virtual DbSet<tbl_City> tbl_City { get; set; }
        public virtual DbSet<tbl_ConceptMapping> tbl_ConceptMapping { get; set; }
        public virtual DbSet<tbl_Country> tbl_Country { get; set; }
        public virtual DbSet<tbl_Curriculum> tbl_Curriculum { get; set; }
        public virtual DbSet<tbl_CurriculumDetails> tbl_CurriculumDetails { get; set; }
        public virtual DbSet<tbl_Image_Content> tbl_Image_Content { get; set; }
        public virtual DbSet<tbl_Images> tbl_Images { get; set; }
        public virtual DbSet<tbl_Level> tbl_Level { get; set; }
        public virtual DbSet<tbl_Location> tbl_Location { get; set; }
        public virtual DbSet<tbl_Map_Role_Permission> tbl_Map_Role_Permission { get; set; }
        public virtual DbSet<tbl_Map_Role_User> tbl_Map_Role_User { get; set; }
        public virtual DbSet<tbl_Map_School_Board> tbl_Map_School_Board { get; set; }
        public virtual DbSet<tbl_Map_School_Standard> tbl_Map_School_Standard { get; set; }
        public virtual DbSet<tbl_Map_School_Teacher> tbl_Map_School_Teacher { get; set; }
        public virtual DbSet<tbl_Map_Teacher_Standard> tbl_Map_Teacher_Standard { get; set; }
        public virtual DbSet<tbl_Map_User_Section> tbl_Map_User_Section { get; set; }
        public virtual DbSet<tbl_MapParentChild> tbl_MapParentChild { get; set; }
        public virtual DbSet<tbl_MapSchoolTeacherStandard> tbl_MapSchoolTeacherStandard { get; set; }
        public virtual DbSet<tbl_MapTeacherChild> tbl_MapTeacherChild { get; set; }
        public virtual DbSet<tbl_MapTeacherStudentQuiz> tbl_MapTeacherStudentQuiz { get; set; }
        public virtual DbSet<tbl_Nouns> tbl_Nouns { get; set; }
        public virtual DbSet<tbl_ParamDetail> tbl_ParamDetail { get; set; }
        public virtual DbSet<tbl_ParamMaster> tbl_ParamMaster { get; set; }
        public virtual DbSet<tbl_Permission> tbl_Permission { get; set; }
        public virtual DbSet<tbl_Question_Pattern> tbl_Question_Pattern { get; set; }
        public virtual DbSet<tbl_Quiz> tbl_Quiz { get; set; }
        public virtual DbSet<tbl_QuizDetails> tbl_QuizDetails { get; set; }
        public virtual DbSet<tbl_QuizResponse> tbl_QuizResponse { get; set; }
        public virtual DbSet<tbl_Role> tbl_Role { get; set; }
        public virtual DbSet<tbl_School> tbl_School { get; set; }
        public virtual DbSet<tbl_Solutions> tbl_Solutions { get; set; }
        public virtual DbSet<tbl_Staging> tbl_Staging { get; set; }
        public virtual DbSet<tbl_Standard> tbl_Standard { get; set; }
        public virtual DbSet<tbl_Standard_Level_Board_Mapping> tbl_Standard_Level_Board_Mapping { get; set; }
        public virtual DbSet<tbl_State> tbl_State { get; set; }
        public virtual DbSet<tbl_Subject> tbl_Subject { get; set; }
        public virtual DbSet<tbl_SubTopic> tbl_SubTopic { get; set; }
        public virtual DbSet<tbl_Topic> tbl_Topic { get; set; }
        public virtual DbSet<tbl_UnitDetails> tbl_UnitDetails { get; set; }
        public virtual DbSet<tbl_UnitMaster> tbl_UnitMaster { get; set; }
        public virtual DbSet<tbl_UrlExpire> tbl_UrlExpire { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
        public virtual DbSet<tbl_UserDetails> tbl_UserDetails { get; set; }
        public virtual DbSet<tbl_UserLog> tbl_UserLog { get; set; }
        public virtual DbSet<tbl_UserType> tbl_UserType { get; set; }
    
        public virtual ObjectResult<StudentDashboard_Result> StudentDashboard(Nullable<System.Guid> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StudentDashboard_Result>("StudentDashboard", userIdParameter);
        }
    
        public virtual int TeacherDashboard(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TeacherDashboard", idParameter);
        }
    
        public virtual ObjectResult<Student_Dashboard_Result> Student_Dashboard(Nullable<System.Guid> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Student_Dashboard_Result>("Student_Dashboard", userIdParameter);
        }
    }
}
